package it.polimi.ingsw.client.GUI;

public enum Clickable {
    ISLAND,ISLAND_STUDENT,CLOUD_STUDENT,LOBBY_STUDENT,
    PERSONALITY_CARD_STUDENT,
    TABLE_STUDENT,ASSISTANT,CLOUD,PERSONALITY,TABLE, COLOR
}
